version: '3.1'

services:
  mongo:
    image: mongo:focal
    restart: always
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      TZ: Asia/Shanghai
      MONGODB_DATABASE: jile-app
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
  mongo-express:
    image: mongo-express
    container_name: mongoAdmin
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME:
      ME_CONFIG_MONGODB_ADMINPASSWORD:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/